### ISSUE TITLE
does not compile under cygwin

### ISSUE THREAD

**Issue by chris-hawley** [opencog/cogutils#46] opened 2016-05-12 15:16 UTC
I know there is another issue open but since this project is pretty actively developed, that issues seems outdated. below is the relevant output. Let me know if you want me to zip the whole directory or provide further information. 

 
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Build type: Release
-- Looking for include file bfd.h
-- Looking for include file bfd.h - not found
-- BFD not found
-- Binutils-dev missing: No pretty stack-trace printing.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105800 found.
-- Found PythonInterp: /usr/bin/python (found version "2.7.10")
-- Cxxtest was not found. Make sure CXXTEST_BIN_DIR is set.
-- CxxTest missing: needed for unit tests.
-- Looking for include file libiberty.h
-- Looking for include file libiberty.h - found
-- Found libiberty: /usr/lib/libiberty.a
-- Libiberty found.
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.11")

The following components will be built:
-----------------------------------------------
   Doxygen     - Code documentation.
   Util        - General utility library.

The following components WILL NOT be built:
-----------------------------------------------
   StackPrint  - Pretty printing of stack traces.
   Unit tests  - Unit tests.

-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/c/Users/chrid/Desktop/opencog/cogutils/build2

chrid@DESKTOP-2HSP4B9 /cygdrive/c/Users/chrid/Desktop/opencog/cogutils/build2
$ make
Scanning dependencies of target cogutil
[  4%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/ansi.cc.o
[  9%] Building C object opencog/util/CMakeFiles/cogutil.dir/backtrace-symbols.c.o
[ 14%] Building C object opencog/util/CMakeFiles/cogutil.dir/cluster.c.o
[ 19%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/Config.cc.o
[ 23%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/exceptions.cc.o
[ 28%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/files.cc.o
[ 33%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/lazy_normal_selector.cc.o
[ 38%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/lazy_random_selector.cc.o
[ 42%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/lazy_selector.cc.o
[ 47%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/log_prog_name.cc.o
[ 52%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/Logger.cc.o
[ 57%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/misc.cc.o
[ 61%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/mt19937ar.cc.o
[ 66%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/oc_assert.cc.o
[ 71%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/oc_omp.cc.o
[ 76%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/octime.cc.o
[ 80%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/platform.cc.o
[ 85%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/StringManipulator.cc.o
[ 90%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/StringTokenizer.cc.o
[ 95%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/tree.cc.o
[100%] Linking CXX shared library cygcogutil.dll
Error copying file "/cygdrive/c/Users/chrid/Desktop/opencog/cogutils/build2/opencog/util/cygcogutil.dll" to "/cygdrive/c/Users/chrid/Desktop/opencog/cogutils/build2/tests/util/".
opencog/util/CMakeFiles/cogutil.dir/build.make:592: recipe for target 'opencog/util/cygcogutil.dll' failed
make[2]: *** [opencog/util/cygcogutil.dll] Error 1
make[2]: *** Deleting file 'opencog/util/cygcogutil.dll'
CMakeFiles/Makefile2:155: recipe for target 'opencog/util/CMakeFiles/cogutil.dir/all' failed
make[1]: *** [opencog/util/CMakeFiles/cogutil.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chris-hawley** [comment] 2016-05-12 21:37
it looks the file wasn't named correctly. It passes after renaming a file.

**Comment by chris-hawley** [comment] 2016-05-13 15:22
another bug related to cygwin was found when compiling atomspace. 

https://github.com/opencog/atomspace/issues/781

**Comment by linas** [comment] 2016-06-28 19:10
Clsing, this seems to be a duplicate of bug #32

**Closed by linas** 2016-06-28 19:10 UTC
